# PREFIX
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# SHELL
set-option -g default-shell /opt/homebrew/bin/zsh
set-option -g default-command /opt/homebrew/bin/zsh

# TERM FIX
set -g default-terminal "tmux-256color"
set -g xterm-keys on

# MOUSE
set -g mouse on

# SPLIT
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# NAV (VIM)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# RESIZE
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# INDEX
set -g base-index 1
setw -g pane-base-index 1

# HISTORY
set -g history-limit 10000

# COPY MODE
setw -g mode-keys vi

# RELOAD
bind r source-file ~/.tmux.conf \; display "reloaded"

# SWITCH
bind Tab last-window